### PR TITLE
Add Java wrapper for the API

### PR DESCRIPTION
**Pull request by TheBotBox**
I have added the java alternate for your api to README file. @tapasweni-pathak please review and let me know what you think!

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Thanks for the pull request. Can you please update the title and commit message as

> Add Java wrapper for the API

and content of the PR something as

> # API Wrappers
> -  [Java wrapper](https://github.com/TheBotBox/Horoscope-API) by [TheBotBox](https://github.com/TheBotBox/) 

There is some useful info about writing commit messages [here](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project).

**Comment by TheBotBox** [comment]
Thanks for the suggestions. 
I have made the necessary changes that you have asked for. 
Please review and let me know.

**Comment by tapaswenipathak** [comment]
Thanks for the pull request, I have merged it.

**Comment by TheBotBox** [comment]
Yeah, I have seen it.

Thanks for accepting the pull request.

Have a nice day. :)

**Comment by tapasweni-pathak** [comment]
Oops your comment got deleted by me.

**Comment by tapasweni-pathak** [comment]
Oh your comment got deleted by me (was scripting something).

**Comment by tapaswenipathak** [comment]
Oh your comment got deleted by me (was testing some script).

**Pull request merged**
